import type { Metadata } from "next";
import type { ReactNode } from "react";
{{nextProvidersImport}}
{{nextThemeImport}}
import "./globals.css";

export const metadata: Metadata = {
  title: "{{projectName}}",
  description: "Generated by project-starter"
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body className="{{nextBodyClassName}}">
        {{nextThemeOpen}}
        {{nextProvidersOpen}}
        {children}
        {{nextProvidersClose}}
        {{nextThemeClose}}
      </body>
    </html>
  );
}
